# Generated by Django 5.0.2 on 2024-03-01 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(max_length=10)),
                ('password', models.CharField()),
                ('isVerified', models.BooleanField()),
                ('image', models.URLField()),
                ('linkedin', models.URLField()),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Startup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(max_length=10)),
                ('image', models.URLField()),
                ('name', models.CharField(max_length=255)),
                ('location', models.TextField()),
                ('sector', models.TextField()),
                ('desc', models.TextField()),
                ('pitchdeck', models.URLField()),
                ('revenue', models.IntegerField()),
                ('support', models.TextField()),
                ('website', models.URLField()),
                ('linkedin', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('usermodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='authentication.usermodel')),
                ('typ', models.CharField(max_length=10)),
                ('location', models.TextField()),
                ('desc', models.TextField()),
                ('sector', models.TextField()),
                ('ticket', models.IntegerField()),
                ('stage', models.TextField()),
                ('support', models.TextField()),
                ('website', models.URLField()),
            ],
            bases=('authentication.usermodel',),
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('usermodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='authentication.usermodel')),
                ('location', models.TextField()),
                ('desc', models.TextField()),
                ('interest', models.TextField()),
                ('website', models.URLField()),
            ],
            bases=('authentication.usermodel',),
        ),
        migrations.CreateModel(
            name='Founder',
            fields=[
                ('usermodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='authentication.usermodel')),
                ('phoneNumber', models.CharField()),
                ('startup', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='founder', to='authentication.startup')),
            ],
            bases=('authentication.usermodel',),
        ),
    ]
