# Generated by Django 5.0.2 on 2024-03-01 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_investor_website_alter_partner_website_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investor',
            name='website',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='partner',
            name='website',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='startup',
            name='linkedin',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='startup',
            name='website',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='linkedin',
            field=models.URLField(),
        ),
    ]
