# Generated by Django 5.0.2 on 2024-03-02 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_investor_website_alter_partner_website_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='linkedin',
            field=models.TextField(),
        ),
    ]
