# Generated by Django 4.1 on 2024-03-05 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_founder_phonenumber_alter_usermodel_password'),
        ('authentication', '0006_alter_usermodel_email'),
    ]

    operations = [
    ]
