# Generated by Django 5.0.2 on 2024-03-06 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0006_alter_usermodel_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usermodel", name="isVerified", field=models.IntegerField(),
        ),
    ]
