# Generated by Django 5.0.2 on 2024-03-06 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0007_alter_usermodel_isverified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="startup", name="pitchdeck", field=models.TextField(null=True),
        ),
    ]
