# Generated by Django 5.0.2 on 2024-03-06 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0008_alter_startup_pitchdeck"),
    ]

    operations = [
        migrations.AlterField(
            model_name="startup", name="website", field=models.TextField(),
        ),
    ]
