# Generated by Django 5.0.2 on 2024-03-08 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0009_alter_startup_website"),
    ]

    operations = [
        migrations.AlterField(
            model_name="investor", name="website", field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="partner", name="website", field=models.TextField(),
        ),
    ]
