# Generated by Django 4.1 on 2024-03-08 03:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0007_alter_founder_phonenumber_alter_usermodel_password"),
        ("authentication", "0009_alter_startup_website"),
    ]

    operations = []
