# Generated by Django 5.0.2 on 2024-03-08 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0010_alter_investor_website_alter_partner_website"),
    ]

    operations = [
        migrations.AddField(
            model_name="partner", name="mou", field=models.TextField(default=""),
        ),
    ]
