# Generated by Django 4.1 on 2024-03-09 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_founder_phonenumber_alter_usermodel_password'),
        ('authentication', '0007_merge_20240305_1117'),
        ('authentication', '0011_partner_mou'),
    ]

    operations = [
    ]
