# Generated by Django 4.1 on 2024-03-12 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0010_merge_20240308_0347"),
        ("authentication", "0013_usermodel_rejectionnote"),
    ]

    operations = []
