# Generated by Django 4.1 on 2024-03-12 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0014_merge_20240313_0436"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usermodel",
            name="rejectionNote",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
