# Generated by Django 4.1 on 2024-04-06 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_alter_usermodel_rejectionnote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Top10Startup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rank1', to='authentication.founder')),
                ('rank10', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rank10', to='authentication.founder')),
                ('rank2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rank2', to='authentication.founder')),
                ('rank3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rank3', to='authentication.founder')),
                ('rank4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rank4', to='authentication.founder')),
                ('rank5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rank5', to='authentication.founder')),
                ('rank6', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rank6', to='authentication.founder')),
                ('rank7', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rank7', to='authentication.founder')),
                ('rank8', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rank8', to='authentication.founder')),
                ('rank9', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rank9', to='authentication.founder')),
            ],
        ),
        migrations.AddConstraint(
            model_name='top10startup',
            constraint=models.UniqueConstraint(fields=('rank1', 'rank2', 'rank3', 'rank4', 'rank5', 'rank6', 'rank7', 'rank8', 'rank9', 'rank10'), name='unique_attributes'),
        ),
    ]
