# Generated by Django 4.1 on 2024-04-06 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0015_alter_usermodel_rejectionnote"),
    ]

    operations = [
        migrations.CreateModel(
            name="InvestorOrganization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("typ", models.CharField(max_length=10)),
                ("location", models.TextField()),
                ("desc", models.TextField()),
                ("sector", models.TextField()),
                ("ticket", models.IntegerField()),
                ("stage", models.TextField()),
                ("support", models.TextField()),
                ("website", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="PartnerOrganization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", models.TextField()),
                ("desc", models.TextField()),
                ("interest", models.TextField()),
                ("website", models.TextField()),
                ("mou", models.TextField(default="")),
            ],
        ),
        migrations.RemoveField(model_name="founder", name="phoneNumber",),
        migrations.RemoveField(model_name="investor", name="desc",),
        migrations.RemoveField(model_name="investor", name="location",),
        migrations.RemoveField(model_name="investor", name="sector",),
        migrations.RemoveField(model_name="investor", name="stage",),
        migrations.RemoveField(model_name="investor", name="support",),
        migrations.RemoveField(model_name="investor", name="ticket",),
        migrations.RemoveField(model_name="investor", name="typ",),
        migrations.RemoveField(model_name="investor", name="website",),
        migrations.RemoveField(model_name="partner", name="desc",),
        migrations.RemoveField(model_name="partner", name="interest",),
        migrations.RemoveField(model_name="partner", name="location",),
        migrations.RemoveField(model_name="partner", name="mou",),
        migrations.RemoveField(model_name="partner", name="website",),
        migrations.AddField(
            model_name="usermodel",
            name="phoneNumber",
            field=models.CharField(default="", max_length=12),
        ),
        migrations.AlterField(
            model_name="founder",
            name="startup",
            field=models.OneToOneField(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="founder",
                to="authentication.startup",
            ),
        ),
        migrations.AlterField(
            model_name="usermodel",
            name="rejectionNote",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="investor",
            name="investorOrganization",
            field=models.OneToOneField(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="investor",
                to="authentication.investororganization",
            ),
        ),
        migrations.AddField(
            model_name="partner",
            name="partnerOrganization",
            field=models.OneToOneField(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="partner",
                to="authentication.partnerorganization",
            ),
        ),
    ]
