# Generated by Django 4.1 on 2024-04-06 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0016_investororganization_partnerorganization_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="investororganization",
            name="linkedin",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="investororganization",
            name="logo",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="investororganization",
            name="name",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="partnerorganization",
            name="linkedin",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="partnerorganization",
            name="logo",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="partnerorganization",
            name="name",
            field=models.CharField(default="", max_length=255),
        ),
    ]
