# Generated by Django 4.1 on 2024-04-06 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_top10startup_top10startup_unique_attributes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='top10startup',
            name='rank1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rank1', to='authentication.startup'),
        ),
        migrations.AlterField(
            model_name='top10startup',
            name='rank10',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rank10', to='authentication.startup'),
        ),
        migrations.AlterField(
            model_name='top10startup',
            name='rank2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rank2', to='authentication.startup'),
        ),
        migrations.AlterField(
            model_name='top10startup',
            name='rank3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rank3', to='authentication.startup'),
        ),
        migrations.AlterField(
            model_name='top10startup',
            name='rank4',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rank4', to='authentication.startup'),
        ),
        migrations.AlterField(
            model_name='top10startup',
            name='rank5',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rank5', to='authentication.startup'),
        ),
        migrations.AlterField(
            model_name='top10startup',
            name='rank6',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rank6', to='authentication.startup'),
        ),
        migrations.AlterField(
            model_name='top10startup',
            name='rank7',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rank7', to='authentication.startup'),
        ),
        migrations.AlterField(
            model_name='top10startup',
            name='rank8',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rank8', to='authentication.startup'),
        ),
        migrations.AlterField(
            model_name='top10startup',
            name='rank9',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rank9', to='authentication.startup'),
        ),
    ]
