# Generated by Django 4.1 on 2024-04-11 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0017_investororganization_linkedin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='phoneNumber',
            field=models.CharField(default='', max_length=16),
        ),
    ]
