# Generated by Django 4.1 on 2024-04-06 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0017_alter_top10startup_rank1_alter_top10startup_rank10_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='top10startup',
            name='unique_attributes',
        ),
    ]
