# Generated by Django 4.1 on 2024-04-30 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0018_alter_usermodel_phonenumber'),
        ('authentication', '0018_remove_top10startup_unique_attributes'),
    ]

    operations = [
    ]
