# Generated by Django 4.1 on 2024-05-11 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0019_merge_20240430_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='Top10Temp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank1', models.IntegerField()),
                ('rank2', models.IntegerField()),
                ('rank3', models.IntegerField()),
                ('rank4', models.IntegerField()),
                ('rank5', models.IntegerField()),
                ('rank6', models.IntegerField()),
                ('rank7', models.IntegerField()),
                ('rank8', models.IntegerField()),
                ('rank9', models.IntegerField()),
                ('rank10', models.IntegerField()),
            ],
        ),
    ]
