# Generated by Django 4.1 on 2024-05-11 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0020_top10temp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='top10temp',
            name='rank1',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='top10temp',
            name='rank10',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='top10temp',
            name='rank2',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='top10temp',
            name='rank3',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='top10temp',
            name='rank4',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='top10temp',
            name='rank5',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='top10temp',
            name='rank6',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='top10temp',
            name='rank7',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='top10temp',
            name='rank8',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='top10temp',
            name='rank9',
            field=models.TextField(),
        ),
    ]
