# Generated by Django 4.1 on 2024-05-12 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0021_alter_top10temp_rank1_alter_top10temp_rank10_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Top10Temp',
        ),
        migrations.AlterField(
            model_name='top10startup',
            name='rank1',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='top10startup',
            name='rank10',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='top10startup',
            name='rank2',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='top10startup',
            name='rank3',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='top10startup',
            name='rank4',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='top10startup',
            name='rank5',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='top10startup',
            name='rank6',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='top10startup',
            name='rank7',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='top10startup',
            name='rank8',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='top10startup',
            name='rank9',
            field=models.TextField(),
        ),
    ]
