# Generated by Django 4.1 on 2024-05-14 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_alter_event_desc_alter_event_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='rejectionNote',
            field=models.TextField(blank=True, default=''),
        ),
    ]
