# Generated by Django 5.0.2 on 2024-02-18 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dummy',
            name='id_dummy',
            field=models.BigIntegerField(),
        ),
    ]
