# Generated by Django 4.1 on 2024-03-08 03:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("showcase", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="postimage",
            name="image",
        ),
        migrations.AddField(
            model_name="postimage",
            name="image_url",
            field=models.TextField(null=True),
        ),
    ]
