# Generated by Django 4.1 on 2024-03-12 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0015_alter_usermodel_rejectionnote"),
        ("showcase", "0004_rename_image_url_postimage_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="like",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="liked_posts",
                to="authentication.usermodel",
            ),
        ),
        migrations.AlterField(
            model_name="showcasepost",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="showcase_posts",
                to="authentication.usermodel",
            ),
        ),
    ]
