# Generated by Django 5.0.2 on 2024-03-01 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaryentries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales', models.PositiveIntegerField(default=0)),
                ('revenue', models.PositiveIntegerField(default=0)),
                ('user', models.PositiveIntegerField(default=0)),
                ('lessonLearned', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Founder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='diary_entries',
        ),
    ]
