# Generated by Django 4.1 on 2024-03-01 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diaryentries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('founder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='diaryentries.founder')),
            ],
        ),
        # migrations.DeleteModel(
        #     name='Song',
        # ),
    ]
