# Generated by Django 4.1 on 2024-03-01 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diaryentries', '0002_entry_delete_song'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='founder',
            name='founder_id',
        ),
    ]
