# Generated by Django 5.0.2 on 2024-03-07 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaryentries', '0002_entry_founder_delete_diary_entries'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='founder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='diaryentries.founder'),
        ),
    ]
