# Generated by Django 4.1 on 2024-03-01 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diaryentries', '0003_remove_founder_founder_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Entry',
        ),
    ]
