# Generated by Django 5.0.2 on 2024-03-07 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_usermodel_email'),
        ('diaryentries', '0003_entry_founder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='founder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='authentication.founder'),
        ),
        migrations.DeleteModel(
            name='Founder',
        ),
    ]
