# Generated by Django 4.1 on 2024-03-01 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diaryentries', '0004_delete_entry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales', models.PositiveIntegerField()),
                ('revenue', models.PositiveIntegerField()),
                ('user', models.PositiveIntegerField()),
                ('lessonLearned', models.TextField()),
                ('founderId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='diaryentries.founder')),
            ],
        ),
    ]
