# Generated by Django 4.1 on 2024-03-01 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diaryentries', '0005_entry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Entry',
        ),
    ]
