# Generated by Django 4.1 on 2024-03-01 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diaryentries', '0007_entry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='founderId',
            new_name='founder',
        ),
    ]
