# Generated by Django 4.1 on 2024-03-02 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_founder_phonenumber_alter_usermodel_password'),
        ('diaryentries', '0008_rename_founderid_entry_founder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='founder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='authentication.founder'),
        ),
        migrations.DeleteModel(
            name='Founder',
        ),
    ]
