# Generated by Django 4.1 on 2024-03-06 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaryentries', '0011_alter_entry_revenue_alter_entry_sales_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='revenue',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='sales',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='user',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
