# Generated by Django 4.1 on 2024-03-07 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaryentries', '0013_alter_entry_revenue_alter_entry_sales_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='lessonLearned',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='entry',
            name='revenue',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='entry',
            name='sales',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='entry',
            name='user',
            field=models.PositiveIntegerField(),
        ),
    ]
