# Generated by Django 4.1 on 2024-03-09 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diaryentries', '0004_alter_entry_founder_delete_founder'),
        ('diaryentries', '0014_alter_entry_lessonlearned_alter_entry_revenue_and_more'),
    ]

    operations = [
    ]
