# Generated by Django 4.1 on 2024-04-02 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_alter_usermodel_rejectionnote'),
        ('diaryentries', '0017_followtable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followtable',
            name='founder',
        ),
    ]
