# Generated by Django 4.1 on 2024-04-02 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diaryentries', '0018_remove_followtable_founder_followtable_startup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FollowTable',
        ),
    ]
